# fly.toml app configuration file generated for material-colors-api on 2023-07-30T01:52:31+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "material-colors-api"
primary_region = "ams"

[env]
  PORT = "8080"

[processes]
  app = "run --allow-net ./example.ts"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
